package com.trinetra.dto.core;

import com.trinetra.service.ai.OllamaService;
import org.springframework.stereotype.Component;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

@Component
public class BiasDetector {

    private final OllamaService ollamaService;

    public BiasDetector(OllamaService ollamaService) {
        this.ollamaService = ollamaService;
    }

    public List<String> detect(String transcript) {
        if (transcript == null || transcript.isBlank()) {
            return Collections.singletonList("Cannot run evaluation on empty text transcript data.");
        }

        String prompt = "Detect supervisor or evaluator bias in the transcript:\n\n" + transcript;
        String response = ollamaService.analyzeWithModel(prompt);

        if (response == null || response.isBlank()) {
            return Collections.emptyList();
        }

        return Arrays.stream(response.split("\n"))
                .map(String::trim)
                // Sanitizes markdown list bullets (- or *) if generated by the model
                .map(s -> s.replaceAll("^[-*]\\s+", "")) 
                .filter(s -> !s.isEmpty())
                .toList();
    }
}